from __future__ import annotations

import re
from typing import Any

from .vibecad_skill import VibeCADSkill


class LocalRuleBasedProvider:
    """Offline provider used when no LLM credentials are configured.

    The provider keeps the same interface as cloud models. It delegates to the
    existing VibeCAD planner so tests and local development remain deterministic.
    """

    name = "local-rule-based"

    def __init__(self, vibecad: VibeCADSkill) -> None:
        self.vibecad = vibecad

    def generate_design_json(self, prompt: str, schema: dict[str, Any]) -> dict[str, Any]:
        plan = self.vibecad.build_plan(self._prepare_prompt(prompt))
        plan["source_brief"] = prompt.strip()
        self._patch_local_parse(plan, prompt)
        plan.setdefault("schema_version", schema.get("schema_version", "vibecad.design.v1"))
        plan.setdefault("planner_notes", [])
        plan["planner_notes"].append("Generated by local fallback provider.")
        return plan

    @staticmethod
    def _prepare_prompt(prompt: str) -> str:
        normalized = prompt.replace("×", "x").replace("Φ", " dia ").replace("φ", " dia ").replace("⌀", " dia ")
        token_map = (
            ("中间", " center "),
            ("中心", " center "),
            ("安装板", " plate "),
            ("圆角", " fillet "),
            ("倒角", " chamfer "),
            ("螺纹", " threaded "),
            ("攻丝", " tapped "),
            ("铝", " aluminum "),
            ("材料", " material "),
        )
        for source, target in token_map:
            normalized = normalized.replace(source, f"{source} {target}")
        if re.search(r"(?:两侧|两边)\s*(?:各)?\s*(?:两个|2个|2)\s*M(?:3|4|5|6|8|10)", prompt, re.IGNORECASE):
            normalized += " 4 holes"
        return normalized

    @staticmethod
    def _patch_local_parse(plan: dict[str, Any], prompt: str) -> None:
        side_thread = re.search(r"(?:两侧|两边)\s*(?:各)?\s*(?:两个|2个|2)\s*(M(?:3|4|5|6|8|10))", prompt, re.IGNORECASE)
        fillet = re.search(r"R\s*(\d+(?:\.\d+)?)", prompt, re.IGNORECASE)
        for feature in plan.get("features", []):
            params = feature.setdefault("params", {})
            if side_thread and feature.get("type") == "threaded_hole":
                params["thread"] = side_thread.group(1).upper()
                params["count"] = 4
                params["position"] = "two_sides_symmetric"
            if fillet and feature.get("type") == "fillet":
                params["radius"] = float(fillet.group(1))


class UnconfiguredRemoteProvider:
    """Placeholder adapter for remote model families.

    Real providers can subclass or replace this with API-specific code while
    preserving the ModelProvider protocol.
    """

    def __init__(self, name: str) -> None:
        self.name = name

    def generate_design_json(self, prompt: str, schema: dict[str, Any]) -> dict[str, Any]:
        raise RuntimeError(f"{self.name} provider is not configured.")
